### ISSUE TITLE
Error / `require': cannot load such file -- mimemagic/overlay (LoadError)

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#193]
### rails c ができなくなった
```
rails c                       
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require': cannot load such file -- mimemagic/overlay (LoadError)
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:44:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/carrierwave-2.2.0/lib/carrierwave/sanitized_file.rb:5:in `<main>'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `block in require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:291:in `load_dependency'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/activesupport-6.0.3.6/lib/active_support/dependencies.rb:324:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/carrierwave-2.2.0/lib/carrierwave.rb:99:in `<main>'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:74:in `block (2 levels) in require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `each'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:69:in `block in require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `each'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler/runtime.rb:58:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.1.4/lib/bundler.rb:174:in `require'
	from /Users/shota/swipe-matching-app/config/application.rb:7:in `<top (required)>'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'
```

**Comment by hasyrails** [comment]
### mimemagicの関連
[mimemagicの最新動向 - HackMD](https://hackmd.io/@mametter/mimemagic-info-ja)

### 対処
```
 $ bundle update mimemagic
```
で解消？
