### ISSUE TITLE
Error / Column `to_user_id` on table `reactions` does not match column `id` on `users`, which has type `bigint`. 

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#194]
```
$ rails db:migrate
== 20210116051043 CreateReactions: migrating ==================================
-- create_table(:reactions)
rails aborted!
StandardError: An error has occurred, all later migrations canceled:

Column `to_user_id` on table `reactions` does not match column `id` on `users`, which has type `bigint`. To resolve this issue, change the type of the `to_user_id` column on `reactions` to be :bigint. (For example `t.bigint :to_user_id`).
Original message: Mysql2::Error: Referencing column 'to_user_id' and referenced column 'id' in foreign key constraint 'fk_rails_d823e36d5f' are incompatible.
/Users/shota/swipe-matching-app/db/migrate/20210116051043_create_reactions.rb:3:in `change'
/Users/shota/swipe-matching-app/bin/rails:9:in `<top (required)>'
/Users/shota/swipe-matching-app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
ActiveRecord::MismatchedForeignKey: Column `to_user_id` on table `reactions` does not match column `id` on `users`, which has type `bigint`. To resolve this issue, change the type of the `to_user_id` column on `reactions` to be :bigint. (For example `t.bigint :to_user_id`).
Original message: Mysql2::Error: Referencing column 'to_user_id' and referenced column 'id' in foreign key constraint 'fk_rails_d823e36d5f' are incompatible.
/Users/shota/swipe-matching-app/db/migrate/20210116051043_create_reactions.rb:3:in `change'
/Users/shota/swipe-matching-app/bin/rails:9:in `<top (required)>'
/Users/shota/swipe-matching-app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'

Caused by:
Mysql2::Error: Referencing column 'to_user_id' and referenced column 'id' in foreign key constraint 'fk_rails_d823e36d5f' are incompatible.
/Users/shota/swipe-matching-app/db/migrate/20210116051043_create_reactions.rb:3:in `change'
/Users/shota/swipe-matching-app/bin/rails:9:in `<top (required)>'
/Users/shota/swipe-matching-app/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by hasyrails** [comment]
Userモデルのidは外部キーとして使われている
idカラムをinteger → stringに変更しようとした時、
外部キーもstring型として定義しなければ型定義の不整合でエラー

**Comment by hasyrails** [comment]
``` ruby
class CreateReactions < ActiveRecord::Migration[6.0]
  def change
    create_table :reactions do |t|
      t.references :to_user, null: false, foreign_key: { to_table: :users }, type: :string 
      # 外部キーとして使うカラムをstring型として明示する
```
