### ISSUE TITLE
RSpec / 中間テーブルでhas_many throughアソシエーションされているレコードのfactoryを作成する

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#211]
### 状況
RSpec / System Spec(ユーザータイプ画面)　にて、
自分がLike/DisLikeのタイプを選択するユーザーカードを表示するには、
Reactionモデルレコードを作成する必要がある。

#### spec/system/app/users_path_page.rb
``` ruby
describe 'users_pathページ(ユーザータイプページ)' do
  context 'ログイン状態のとき' do
    let!(:user) { create(:user) }
    before do
      visit root_path
      click_on 'ログイン' 
      fill_in 'メールアドレス', with: user.email
      fill_in 'パスワード', with: user.password
      click_on 'ログイン'
    end
    
    context 'ユーザーカードが表示されているとき' do
      let!(:user) { create(:user, :user_with_reactions) }
      it '❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること' do
        # ユーザーカードを表示させる必要がある
          # ❤︎ボタンをクリックする
          find("#like").click
          
          # ユーザーカードが左にスワイプされることを確認する
      end
    end
  end
end
```

**Comment by hasyrails** [comment]
## Reactionモデルレコードに紐づけられたUserモデルレコードを作成できない
### factoryファイル
#### spec/factories/users.rb 
``` ruby
FactoryBot.define do
  factory :user do
    sequence(:name) { |n| "user#{n}" } # 連番
    sequence(:email) { |n| "user#{n}@example.com" } # 連番
    password { 'password' }

    trait :user_with_reactions do
      after(:build) do |user|  # after(:build)とした場合、createの場合もcallbackが走る
        user.reactions << build(:reaction)
        binding.pry
      end
    end
```

#### spec/factories/reactions.rb
``` ruby
FactoryBot.define do
  factory :reaction do
    association :user
    status { ['dislike', 'like'].sample }
  end
end
```

## 実際のテストコードを実行した時のターミナル出力
``` 
$ bundle exec rspec spec/system/app/users_path_page.rb
Run options: include {:focus=>true}

Randomized with seed 5619

users_pathページ(ユーザータイプページ)
  ゲストログイン状態のとき
    ユーザーカードが表示されているとき
Capybara starting Puma...
* Version 4.3.7 , codename: Mysterious Traveller
* Min threads: 0, max threads: 4
* Listening on tcp://127.0.0.1:63778
DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create!` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `User.default_scoped`. (called from block in generate_uuid at /Users/shota/swipe-matching-app/app/models/concerns/id_generator.rb:10)
      ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること (FAILED - 1)

Failures:

  1) users_pathページ(ユーザータイプページ) ゲストログイン状態のとき ユーザーカードが表示されているとき ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること
     Failure/Error: user.reactions << build(:reaction)
     
     NoMethodError:
       undefined method `user=' for #<Reaction:0x00007f94ec580060>
       Did you mean?  to_user=
     # ./spec/factories/users.rb:15:in `block (4 levels) in <main>'
     # ./spec/system/app/users_path_page.rb:82:in `block (4 levels) in <main>'

Top 1 slowest examples (3.35 seconds, 99.9% of total time):
  users_pathページ(ユーザータイプページ) ゲストログイン状態のとき ユーザーカードが表示されているとき ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること
    3.35 seconds ./spec/system/app/users_path_page.rb:83

Finished in 3.35 seconds (files took 3.38 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/app/users_path_page.rb:83 # users_pathページ(ユーザータイプページ) ゲストログイン状態のとき ユーザーカードが表示されているとき ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること

Randomized with seed 5619

```

#### binding.pry　でレコードの状態の確認すらできない？？
``` ruby
  trait :user_with_reactions do
      after(:build) do |user|  # after(:build)とした場合、createの場合もcallbackが走る
        user.reactions << build(:reaction)
        binding.pry # ここでbinding.pryしてuserの形を確認したいが出力されない
      end
    end
```
アソシエーション設定自体が破綻している可能性

**Comment by hasyrails** [comment]
## Userモデル - Reactionモデルのアソシエーションを確認
### 前提
「中間テーブル」　というと**異なる**テーブルのレコードを関連づけるもののイメージが一般だが
```
User ⇄ Comment ⇄ Article 
```
Reactionテーブルは**同一**テーブル内（Userテーブル）のレコードを結びつけるテーブル
```
User ⇄ Reaction
```

## アソシエーション設定
### モデル設定
#### app/models/user.rb
``` ruby
class User < ApplicationRecord
  has_many :reactions, foreign_key: :from_user_id, dependent: :destroy
  has_many :reactions, foreign_key: :to_user_id, dependent: :destroy
```
#### app/models/reaction.rb
``` ruby
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User", foreign_key: :to_user_id
  belongs_to :from_user, class_name: "User", foreign_key: :from_user_id
```
### migrationファイル
#### db/migrate/yyyymmddhhmmss_devise_create_users.rb 
``` ruby
# frozen_string_literal: true

class DeviseCreateUsers < ActiveRecord::Migration[6.0]
  def change
    create_table :users, id: false do |t|
      t.string :id, limit: 36, null: false, primary_key: true
      ## Database authenticatable
      t.string :email,              null: false, default: ""
      t.string :encrypted_password, null: false, default: ""
      ‥ # deviseデフォルト　外部キー追加設定はなし
    end
  end
end
```
#### db/migrate/yyyymmddhhmmss_create_reactions.rb
``` ruby
class CreateReactions < ActiveRecord::Migration[6.0]
  def change
    create_table :reactions do |t|
      t.references :to_user, null: false, foreign_key: { to_table: :users }, type: :string 
      t.references :from_user, null: false, foreign_key: { to_table: :users }, type: :string  
      t.integer :status, null: false

      t.timestamps
    end
  end
end
```
### schemaファイル
#### db/schema.rb
``` ruby
ActiveRecord::Schema.define(version: 2021_03_23_220653) do
  create_table "reactions", options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "to_user_id", null: false
    t.string "from_user_id", null: false
    t.integer "status", null: false
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.index ["from_user_id"], name: "index_reactions_on_from_user_id"
    t.index ["to_user_id"], name: "index_reactions_on_to_user_id"
  end

  create_table "users", id: :string, limit: 36, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8", force: :cascade do |t|
    t.string "email", default: "", null: false
    t.string "encrypted_password", default: "", null: false
    t.string "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.datetime "created_at", precision: 6, null: false
    t.datetime "updated_at", precision: 6, null: false
    t.string "name", null: false
    t.integer "gender", default: 0, null: false
    t.text "self_introduction"
    t.string "profile_image"
    t.integer "role", default: 0
    t.index ["email"], name: "index_users_on_email", unique: true
    t.index ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true
  end

  add_foreign_key "reactions", "users", column: "from_user_id"
  add_foreign_key "reactions", "users", column: "to_user_id"
end

```

**Comment by hasyrails** [comment]
### 留意点 : デフォルトの外部キーの名前から変更した外部キーを使用している
デフォルトのReaction - User間のアソシエーションの外部キーは
```
user_id
```
だが、名前を変更した下記外部キーを使用している
```
from_user_id
to_user_id
```

RSpecのアソシエーションファクトリ作成コードにも反映させる必要がある

**Comment by hasyrails** [comment]
### アソシエーション有のファクトリ作成時の外部キー指定の方法
下記設定でエラー解消

#### 参考
[【FactoryBot】外部参照キーのカラムデータの作成方法 - Qiita](https://qiita.com/j-sunaga/items/ed77d30ede5a8008c2e7)

#### spec/factories/reactions.rb
``` ruby
FactoryBot.define do
  factory :reaction do
    association :from_user, factory: :user # 外部キーの名前を指定
    association :to_user, factory: :user　# 外部キーの名前を指定
    
    status { ['dislike', 'like'].sample }
end

```
