### ISSUE TITLE
RSpec / ActiveRecord::LockWaitTimeout:  Mysql2::Error::TimeoutError: Lock wait timeout exceeded; try restarting transaction

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#212]
#### bundle exec rspecができない
```
$ bundle exec rspec spec/system/app/users_path_page.rb
Run options: include {:focus=>true}

Randomized with seed 4175

users_pathページ(ユーザータイプページ)
  ゲストログイン状態のとき
    ユーザーカードが表示されているとき
^C
RSpec is shutting down and will print the summary report... Interrupt again to force quit.
      ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること (FAILED - 1)

Failures:

  1) users_pathページ(ユーザータイプページ) ゲストログイン状態のとき ユーザーカードが表示されているとき ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること
     Failure/Error: let!(:guest_user) { create(:user) }
     
     ActiveRecord::LockWaitTimeout:
       Mysql2::Error::TimeoutError: Lock wait timeout exceeded; try restarting transaction
     # ./spec/system/app/users_path_page.rb:69:in `block (3 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # Mysql2::Error::TimeoutError:
     #   Lock wait timeout exceeded; try restarting transaction
     #   ./spec/system/app/users_path_page.rb:69:in `block (3 levels) in <main>'

Top 1 slowest examples (51.18 seconds, 100.0% of total time):
  users_pathページ(ユーザータイプページ) ゲストログイン状態のとき ユーザーカードが表示されているとき ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること
    51.18 seconds ./spec/system/app/users_path_page.rb:83

Finished in 51.18 seconds (files took 2.22 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/system/app/users_path_page.rb:83 # users_pathページ(ユーザータイプページ) ゲストログイン状態のとき ユーザーカードが表示されているとき ❤︎ボタンを押すとユーザーカードが右スライドされること/Reactionレコード(like)が作成されること

Randomized with seed 4175
```

**Comment by hasyrails** [comment]
### エラー解消試行
#### 参考
[RSpecを実行すると、 Lock wait timeout exceeded; try restarting transaction mysqlというエラーがでる - Qiita](https://qiita.com/Kiyo_Karl2/items/4d3b372c5b041a2bbb05)

#### 手順
 - ① ```mysql -u root -p```
 - ② ```SHOW ENGINE INNODB STATUS```
```
------------
TRANSACTIONS
------------
Trx id counter 40740
Purge done for trx's n:o < 40726 undo n:o < 0 state: running but idle
History list length 4
LIST OF TRANSACTIONS FOR EACH SESSION:
---TRANSACTION 422048648150344, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 422048648149504, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 422048648148664, not started
0 lock struct(s), heap size 1136, 0 row lock(s)
---TRANSACTION 40733, ACTIVE 541 sec
4 lock struct(s), heap size 1136, 3 row lock(s), undo log entries 1
MySQL thread id 344, OS thread handle 123145383948288, query id 22345 localhost root
Trx read view will not see trx with id >= 40733, sees < 40724
---TRANSACTION 40724, ACTIVE 581 sec
4 lock struct(s), heap size 1136, 5 row lock(s), undo log entries 6
MySQL thread id 343, OS thread handle 123145384251392, query id 22287 localhost root
Trx read view will not see trx with id >= 40724, sees < 40724
``` 
 - ③ ```kill 343```
```
---TRANSACTION 40724, ACTIVE 581 sec
4 lock struct(s), heap size 1136, 5 row lock(s), undo log entries 6
MySQL thread id XXX, ←このXXXの部分をkillする
```
