### ISSUE TITLE
Deploy_03 / Capistranoエラー① : CapistranoでEC２インスタンスへsshログインできていない

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#259]
#### エラーログ 
```
$  bundle exec cap production deploy
This stage is 'production'. Deploying branch is 'master'.
Are you sure? [y/n]
Please enter answer (n): y
00:00 git:wrapper
      01 mkdir -p /tmp
#<Thread:0x00007fdd30b78a58@/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	12: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	11: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	10: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	 9: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/tasks/git.rake:8:in `block (3 levels) in eval_rakefile'
	 8: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
	 7: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 6: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `tap'
	 5: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 4: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:130:in `execute_command'
	 3: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:177:in `with_ssh'
	 2: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/connection_pool.rb:63:in `with'
	 1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/connection_pool.rb:63:in `call'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/net-ssh-6.1.0/lib/net/ssh.rb:268:in `start': Authentication failed for user hasyrails@xx.xxx.xx.xxx (Net::SSH::AuthenticationFailed)
	1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as hasyrails@xx.xxx.xx.xxx: Authentication failed for user hasyrails@xx.xxx.xx.xxx (SSHKit::Runner::ExecuteError)
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as hasyrails@xx.xxx.xx.xxx: Authentication failed for user hasyrails@xx.xxx.xx.xxx


Caused by:
Net::SSH::AuthenticationFailed: Authentication failed for user hasyrails@xx.xxx.xx.xxx

Tasks: TOP => deploy:check => git:check => git:wrapper
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as hasyrails@xx.xxx.xx.xxx: Authentication failed for user hasyrails@xx.xxx.xx.xxx


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


# Logfile created on 2021-04-18 13:55:24 +0900 by logger.rb/66358

  INFO ---------------------------------------------------------------------------

  INFO START 2021-04-18 13:55:24 +0900 cap production deploy

  INFO ---------------------------------------------------------------------------

  INFO [cba4bf88] Running /usr/bin/env mkdir -p /tmp as hasyrails@xx.xxx.xx.xxx

 DEBUG [cba4bf88] Command: /usr/bin/env mkdir -p /tmp

  INFO ---------------------------------------------------------------------------

  INFO START 2021-04-18 13:57:52 +0900 cap production deploy

  INFO ---------------------------------------------------------------------------

  INFO [e308c1e3] Running /usr/bin/env mkdir -p /tmp as hasyrails@xx.xxx.xx.xxx

 DEBUG [e308c1e3] Command: /usr/bin/env mkdir -p /tmp

```

#### Capfile
``` ruby
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
```

#### config/deploy/production.rb
``` ruby
server "xx.xxx.xx.xxx", user: "hasyrails", roles: %w{app db web}
set :ssh_options, {
  keys: %w(~/.ssh/id_rsa),
  forward_agent: true,
  auth_methods: %w(publickey)
}
```

#### config/deploy.rb
``` ruby
namespace :deploy do
  desc "Make sure local git is in sync with remote."

  task :confirm do
    on roles(:app) do
      puts "This stage is '#{fetch(:stage)}'. Deploying branch is '#{fetch(:branch)}'."
      puts 'Are you sure? [y/n]'
      ask :answer, 'n'
      if fetch(:answer) != 'y'
        puts 'deploy stopped'
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      invoke 'deploy'
    end
  end
  
  before :starting, :confirm
end

```

**Comment by hasyrails** [comment]
### 修正
元々のEC2ログインするコマンド
```
 .ssh % ssh -i favimo_EC2.pem ec2-user@xx.xxx.xx.xxx
```
に対応させてproduction.rbを修正する

#### config/deploy/production.rb
``` ruby
 - server "xx.xxx.xx.xxx", user: "hasyrails", roles: %w{app db web}
 + server "xx.xxx.xx.xxx", user: "ec2-user", roles: %w{app db web}

set :ssh_options, {
-  keys: %w(~/.ssh/id_rsa),  # githubのssh通信の鍵
+ keys: %w(~/.ssh/favimo_EC2.pem),  # EC2インスタンスへのログイン向け公開鍵
  forward_agent: true,
  auth_methods: %w(publickey)
}
```
