### ISSUE TITLE
deploy_03 / capistranoエラー② : Permission denied (publickey).

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#260]
### Capistranoエラーログ 
```
$ bundle exec cap production deploy
This stage is 'production'. Deploying branch is 'master'.
Are you sure? [y/n]
Please enter answer (n): y
00:00 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 ec2-user@xx.xxx.xx.xxx 2.186s
      Uploading /tmp/git-ssh-5cd9275dc8b937e40f08.sh 100.0%
      02 chmod 700 /tmp/git-ssh-5cd9275dc8b937e40f08.sh
    ✔ 02 ec2-user@xx.xxx.xx.xxx 0.411s
00:03 git:check
      01 git ls-remote git@github.com:hasyrails/favimo.git HEAD
      01 Permission denied (publickey).
      01 fatal: Could not read from remote repository.
      01
      01 Please make sure you have the correct access rights
      01 and the repository exists.
#<Thread:0x00007f996bb5efd0@/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	12: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	11: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	10: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/tasks/git.rake:18:in `block (3 levels) in eval_rakefile'
	 9: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:100:in `with'
	 8: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/tasks/git.rake:19:in `block (4 levels) in eval_rakefile'
	 7: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/git.rb:40:in `check_repo_is_reachable'
	 6: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/git.rb:83:in `git'
	 5: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': git exit status: 128 (SSHKit::Command::Failed)
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
	1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as ec2-user@xx.xxx.xx.xxx: git exit status: 128 (SSHKit::Runner::ExecuteError)
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ec2-user@xx.xxx.xx.xxx: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


Caused by:
SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Tasks: TOP => deploy:check => git:check
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ec2-user@xx.xxx.xx.xxx: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


Please make sure you have the correct access rights

and the repository exists.

  INFO ---------------------------------------------------------------------------

  INFO START 2021-04-18 19:27:07 +0900 cap production deploy

  INFO ---------------------------------------------------------------------------

  INFO [7fefc278] Running /usr/bin/env mkdir -p /tmp as ec2-user@xx.xxx.xx.xxx

 DEBUG [7fefc278] Command: /usr/bin/env mkdir -p /tmp

  INFO [7fefc278] Finished in 2.186 seconds with exit status 0 (successful).

 DEBUG Uploading /tmp/git-ssh-5cd9275dc8b937e40f08.sh 0.0%

  INFO Uploading /tmp/git-ssh-5cd9275dc8b937e40f08.sh 100.0%

  INFO [120f1355] Running /usr/bin/env chmod 700 /tmp/git-ssh-5cd9275dc8b937e40f08.sh as ec2-user@xx.xxx.xx.xxx

 DEBUG [120f1355] Command: /usr/bin/env chmod 700 /tmp/git-ssh-5cd9275dc8b937e40f08.sh

  INFO [120f1355] Finished in 0.411 seconds with exit status 0 (successful).

  INFO [8e4bb54b] Running /usr/bin/env git ls-remote git@github.com:hasyrails/favimo.git HEAD as ec2-user@xx.xxx.xx.xxx

 DEBUG [8e4bb54b] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-5cd9275dc8b937e40f08.sh" ; /usr/bin/env git ls-remote git@github.com:hasyrails/favimo.git HEAD )

 DEBUG [8e4bb54b] 	Permission denied (publickey).

 DEBUG [8e4bb54b] 	fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.
```

#### Capfile
``` ruby
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
```

#### config/deploy.rb
``` ruby
# config valid for current version and patch releases of Capistrano
lock "~> 3.16.0"

set :application, "favimo"
set :repo_url, "git@github.com:hasyrails/favimo.git"
set :deploy_to, '/var/www/rails'

# Default branch is :master
# ask :branch, `git rev-parse --abbrev-ref HEAD`.chomp

# Default deploy_to directory is /var/www/my_app_name
# set :deploy_to, "/var/www/my_app_name"

# Default value for :format is :airbrussh.
# set :format, :airbrussh

# You can configure the Airbrussh format using :format_options.
# These are the defaults.
# set :format_options, command_output: true, log_file: "log/capistrano.log", color: :auto, truncate: :auto

# Default value for :pty is false
# set :pty, true

# Default value for :linked_files is []
# append :linked_files, "config/database.yml"

# Default value for linked_dirs is []
# append :linked_dirs, "log", "tmp/pids", "tmp/cache", "tmp/sockets", "public/system"

# Default value for default_env is {}
# set :default_env, { path: "/opt/ruby/bin:$PATH" }

# Default value for local_user is ENV['USER']
# set :local_user, -> { `git config user.name`.chomp }

# Default value for keep_releases is 5
# set :keep_releases, 5

# Uncomment the following to require manually verifying the host key before first deploy.
# set :ssh_options, verify_host_key: :secure

namespace :deploy do
  desc "Make sure local git is in sync with remote."

  task :confirm do
    on roles(:app) do
      puts "This stage is '#{fetch(:stage)}'. Deploying branch is '#{fetch(:branch)}'."
      puts 'Are you sure? [y/n]'
      ask :answer, 'n'
      if fetch(:answer) != 'y'
        puts 'deploy stopped'
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      invoke 'deploy'
    end
  end
  
  before :starting, :confirm
end
```

#### config/deploy/production.rb
``` ruby
server "xx.xxx.xx.xxx", user: "ec2-user", roles: %w{app db web}
set :repo_url, "git@github.com:hasyrails/favimo.git"
set :application, "favimo"
set :ssh_options, {
  keys: %w(~/.ssh/favimo_EC2.pem),
  forward_agent: true,
  auth_methods: %w(publickey)
}
set :use_sudo, true
```

**Comment by hasyrails** [comment]
### 対処方針
["Permission denied (publickey)"と表示されたときの対処法 - Qiita](https://qiita.com/hikaru-light/items/be46dfab4e52ee55a134)
 上記の手順を踏んでもエラー解消できず

↓　

### 方針変更
> そこでSSHではなくHTTPを使ってGitHubのリポジトリにアクセスしてみます。

[Capistranoを使ってデプロイする時に「git ls-remote」でつまづいた
](https://www.tabosque.com/tech/22)

### 修正内容
#### config/deploy/production.rb
``` ruby
server "xx.xxx.xx.xxx", user: "ec2-user", roles: %w{app db web}
# set :repo_url, "git@github.com:hasyrails/favimo.git"   # ssh通信は使わず
set :repo_url, "https://github.com/hasyrails/favimo.git" # HTTPS通信に変更する
set :application, "favimo"
set :ssh_options, {
  keys: %w(~/.ssh/favimo_EC2.pem),
  forward_agent: true,
  auth_methods: %w(publickey)
}
set :use_sudo, true
```
