### ISSUE TITLE
deploy_03 / capistranoエラー③ : mkdir stderr: mkdir: ディレクトリ `/var/www/rails/favimo/shared' を作成できません: Permission denied mkdir: ディレクトリ `/var/www/rails/favimo/releases' を作成できません: Permission denied

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#261]
### capistranoエラーログ 
```
This stage is 'production'. Deploying branch is 'master'.
Are you sure? [y/n]
Please enter answer (n): y
00:00 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 ec2-user@xx.xxx.xx.xxx 1.272s
      Uploading /tmp/git-ssh-d40e63108334bae0db0a.sh 100.0%
      02 chmod 700 /tmp/git-ssh-d40e63108334bae0db0a.sh
    ✔ 02 ec2-user@xx.xxx.xx.xxx 0.488s
00:02 git:check
      01 git ls-remote https://github.com/hasyrails/favimo.git HEAD
      01 65c36a99df625a161d834e26c1b9eb385f34d222	HEAD
    ✔ 01 ec2-user@xx.xxx.xx.xxx 0.729s
00:03 deploy:check:directories
      01 mkdir -p /var/www/rails/favimo/shared /var/www/rails/favimo/releases
      01 mkdir:
      01 ディレクトリ `/var/www/rails/favimo/shared' を作成できません
      01 : Permission denied
      01
      01 mkdir:
      01 ディレクトリ `/var/www/rails/favimo/releases' を作成できません
      01 : Permission denied
      01
#<Thread:0x00007f92d96780e0@/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	9: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	8: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	7: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	6: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/tasks/deploy.rake:65:in `block (4 levels) in <top (required)>'
	5: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
	4: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	3: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `tap'
	2: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': mkdir exit status: 1 (SSHKit::Command::Failed)
mkdir stdout: Nothing written
mkdir stderr: mkdir: ディレクトリ `/var/www/rails/favimo/shared' を作成できません: Permission denied
mkdir: ディレクトリ `/var/www/rails/favimo/releases' を作成できません: Permission denied
	1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as ec2-user@xx.xxx.xx.xxx: mkdir exit status: 1 (SSHKit::Runner::ExecuteError)
mkdir stdout: Nothing written
mkdir stderr: mkdir: ディレクトリ `/var/www/rails/favimo/shared' を作成できません: Permission denied
mkdir: ディレクトリ `/var/www/rails/favimo/releases' を作成できません: Permission denied
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as ec2-user@xx.xxx.xx.xxx: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: mkdir: ディレクトリ `/var/www/rails/favimo/shared' を作成できません: Permission denied
mkdir: ディレクトリ `/var/www/rails/favimo/releases' を作成できません: Permission denied


Caused by:
SSHKit::Command::Failed: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: mkdir: ディレクトリ `/var/www/rails/favimo/shared' を作成できません: Permission denied
mkdir: ディレクトリ `/var/www/rails/favimo/releases' を作成できません: Permission denied

Tasks: TOP => deploy:check:directories
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as ec2-user@xx.xxx.xx.xxx: mkdir exit status: 1
mkdir stdout: Nothing written
mkdir stderr: mkdir: ディレクトリ `/var/www/rails/favimo/shared' を作成できません: Permission denied
mkdir: ディレクトリ `/var/www/rails/favimo/releases' を作成できません: Permission denied


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


  INFO [364d84ac] Finished in 1.272 seconds with exit status 0 (successful).

 DEBUG Uploading /tmp/git-ssh-d40e63108334bae0db0a.sh 0.0%

  INFO Uploading /tmp/git-ssh-d40e63108334bae0db0a.sh 100.0%

  INFO [d3631d10] Running /usr/bin/env chmod 700 /tmp/git-ssh-d40e63108334bae0db0a.sh as ec2-user@xx.xxx.xx.xxx

 DEBUG [d3631d10] Command: /usr/bin/env chmod 700 /tmp/git-ssh-d40e63108334bae0db0a.sh

  INFO [d3631d10] Finished in 0.488 seconds with exit status 0 (successful).

  INFO [039171a4] Running /usr/bin/env git ls-remote https://github.com/hasyrails/favimo.git HEAD as ec2-user@xx.xxx.xx.xxx

 DEBUG [039171a4] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-d40e63108334bae0db0a.sh" ; /usr/bin/env git ls-remote https://github.com/hasyrails/favimo.git HEAD )

 DEBUG [039171a4] 	65c36a99df625a161d834e26c1b9eb385f34d222	HEAD

  INFO [039171a4] Finished in 0.729 seconds with exit status 0 (successful).

  INFO [3b64eb59] Running /usr/bin/env mkdir -p /var/www/rails/favimo/shared /var/www/rails/favimo/releases as ec2-user@xx.xxx.xx.xxx

 DEBUG [3b64eb59] Command: /usr/bin/env mkdir -p /var/www/rails/favimo/shared /var/www/rails/favimo/releases

 DEBUG [3b64eb59] 	mkdir: 

 DEBUG [3b64eb59] 	ディレクトリ `/var/www/rails/favimo/shared' を作成できません

 DEBUG [3b64eb59] 	: Permission denied

 DEBUG [3b64eb59] 	

 DEBUG [3b64eb59] 	mkdir: 

 DEBUG [3b64eb59] 	ディレクトリ `/var/www/rails/favimo/releases' を作成できません

 DEBUG [3b64eb59] 	: Permission denied

 DEBUG [3b64eb59] 	

```

#### Capfile
``` ruby
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }
```

#### config/deploy/production.rb
``` ruby
server "xx.xxx.xx.xxx", user: "ec2-user", roles: %w{app db web}
set :repo_url, "https://github.com/hasyrails/favimo.git" 
set :application, "favimo"
set :ssh_options, {
  keys: %w(~/.ssh/favimo_EC2.pem),
  forward_agent: true,
  auth_methods: %w(publickey)
}
set :use_sudo, true

```

#### config/deploy.rb
``` ruby
# config valid for current version and patch releases of Capistrano
lock "~> 3.16.0"

set :application, "favimo"
set :repo_url, "git@github.com:hasyrails/favimo.git"
set :deploy_to, '/var/www/rails'

# Default branch is :master
# ask :branch, `git rev-parse --abbrev-ref HEAD`.chomp

# Default deploy_to directory is /var/www/my_app_name
# set :deploy_to, "/var/www/my_app_name"

# Default value for :format is :airbrussh.
# set :format, :airbrussh

# You can configure the Airbrussh format using :format_options.
# These are the defaults.
# set :format_options, command_output: true, log_file: "log/capistrano.log", color: :auto, truncate: :auto

# Default value for :pty is false
# set :pty, true

# Default value for :linked_files is []
# append :linked_files, "config/database.yml"

# Default value for linked_dirs is []
# append :linked_dirs, "log", "tmp/pids", "tmp/cache", "tmp/sockets", "public/system"

# Default value for default_env is {}
# set :default_env, { path: "/opt/ruby/bin:$PATH" }

# Default value for local_user is ENV['USER']
# set :local_user, -> { `git config user.name`.chomp }

# Default value for keep_releases is 5
# set :keep_releases, 5

# Uncomment the following to require manually verifying the host key before first deploy.
# set :ssh_options, verify_host_key: :secure

namespace :deploy do
  desc "Make sure local git is in sync with remote."

  task :confirm do
    on roles(:app) do
      puts "This stage is '#{fetch(:stage)}'. Deploying branch is '#{fetch(:branch)}'."
      puts 'Are you sure? [y/n]'
      ask :answer, 'n'
      if fetch(:answer) != 'y'
        puts 'deploy stopped'
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      invoke 'deploy'
    end
  end
  
  before :starting, :confirm
end
```

**Comment by hasyrails** [comment]
### ログインをece-userではなく作業用ユーザーでログインする

#### 作業用ユーザーの作成(EC2インスタンスサーバー内)
済。

#### 鍵の設定(ローカル内)
[EC2内に作業用ユーザーを追加して、新規鍵を元にSSH接続する手順 - Qiita](https://qiita.com/sayama0402/items/25fc56ca6caed852ca4c)

#### config/deploy/production.rb 修正
sshログイン設定を修正

##### config/deploy/production.rb
``` ruby
# server "xx.xxx.xx.xxx", user: "ec2-user", roles: %w{app db web}
server "xx.xxx.xx.xxx", user: "hasyrails", roles: %w{app db web} 
  # 作業用ユーザー"hasyrails"でログインする
set :repo_url, "https://github.com/hasyrails/favimo.git" 
set :application, "favimo"
set :ssh_options, {
  # keys: %w(~/.ssh/favimo_EC2.pem),
  keys: %w(~/.ssh/favimo_rsa_hasyrails),
    # 新たに作成した作業用ユーザー用の秘密鍵でログイン
  forward_agent: true,
  auth_methods: %w(publickey)
}
set :use_sudo, true
```
