### ISSUE TITLE
deploy_03 / capistranoエラー④ :  作業用ユーザーでError: Permission denied (publickey)

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#262]
### 変更した点
作業用ユーザーでcapistranoログインするように設定した

### capistranoエラーログ 
```
$ bundle exec cap production deploy
This stage is 'production'. Deploying branch is 'master'.
Are you sure? [y/n]
Please enter answer (n): y
00:00 git:wrapper
     01 mkdir -p /tmp
   ✔ 01 hasyrails@xx.xxx.xx.xxx 1.278s
     Uploading /tmp/git-ssh-a2cf71ce9afdb92753f7.sh 100.0%
     02 chmod 700 /tmp/git-ssh-a2cf71ce9afdb92753f7.sh
   ✔ 02 hasyrails@xx.xxx.xx.xxx 0.459s
00:02 git:check
     01 git ls-remote https://github.com/hasyrails/favimo.git HEAD
     01 Permission denied (publickey).
     01 fatal: Could not read from remote repository.
     01
     01 Please make sure you have the correct access rights
     01 and the repository exists.
#<Thread:0x00007fe8e8ea6298@/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
 13: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
 12: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
 11: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
 10: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/tasks/git.rake:18:in `block (3 levels) in eval_rakefile'
  9: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:100:in `with'
  8: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/tasks/git.rake:19:in `block (4 levels) in eval_rakefile'
  7: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/git.rb:40:in `check_repo_is_reachable'
  6: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-3.16.0/lib/capistrano/scm/git.rb:83:in `git'
  5: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
  4: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
  3: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `tap'
  2: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
  1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': git exit status: 128 (SSHKit::Command::Failed)
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
 1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute': Exception while executing as hasyrails@xx.xxx.xx.xxx: git exit status: 128 (SSHKit::Runner::ExecuteError)
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as hasyrails@xx.xxx.xx.xxx: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


Caused by:
SSHKit::Command::Failed: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Tasks: TOP => deploy:check => git:check
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as hasyrails@xx.xxx.xx.xxx: git exit status: 128
git stdout: Nothing written
git stderr: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


Please make sure you have the correct access rights

and the repository exists.

 INFO ---------------------------------------------------------------------------

 INFO START 2021-04-20 07:38:15 +0900 cap production deploy

 INFO ---------------------------------------------------------------------------

 INFO [9372d3c9] Running /usr/bin/env mkdir -p /tmp as hasyrails@xx.xxx.xx.xxx

DEBUG [9372d3c9] Command: /usr/bin/env mkdir -p /tmp

 INFO [9372d3c9] Finished in 1.278 seconds with exit status 0 (successful).

DEBUG Uploading /tmp/git-ssh-a2cf71ce9afdb92753f7.sh 0.0%

 INFO Uploading /tmp/git-ssh-a2cf71ce9afdb92753f7.sh 100.0%

 INFO [bcdf9276] Running /usr/bin/env chmod 700 /tmp/git-ssh-a2cf71ce9afdb92753f7.sh as hasyrails@xx.xxx.xx.xxx

DEBUG [bcdf9276] Command: /usr/bin/env chmod 700 /tmp/git-ssh-a2cf71ce9afdb92753f7.sh

 INFO [bcdf9276] Finished in 0.459 seconds with exit status 0 (successful).

 INFO [f49f609c] Running /usr/bin/env git ls-remote https://github.com/hasyrails/favimo.git HEAD as hasyrails@xx.xxx.xx.xxx

DEBUG [f49f609c] Command: ( export GIT_ASKPASS="/bin/echo" GIT_SSH="/tmp/git-ssh-a2cf71ce9afdb92753f7.sh" ; /usr/bin/env git ls-remote https://github.com/hasyrails/favimo.git HEAD )

DEBUG [f49f609c] 	Permission denied (publickey).

DEBUG [f49f609c] 	fatal: Could not read from remote repository.



Please make sure you have the correct access rights

and the repository exists.

```

#### Capfile
``` ruby
# Load DSL and set up stages
require "capistrano/setup"

# Include default deployment tasks
require "capistrano/deploy"

# Load the SCM plugin appropriate to your project:
#
# require "capistrano/scm/hg"
# install_plugin Capistrano::SCM::Hg
# or
# require "capistrano/scm/svn"
# install_plugin Capistrano::SCM::Svn
# or
require "capistrano/scm/git"
install_plugin Capistrano::SCM::Git

# Include tasks from other gems included in your Gemfile
#
# For documentation on these, see for example:
#
#   https://github.com/capistrano/rvm
#   https://github.com/capistrano/rbenv
#   https://github.com/capistrano/chruby
#   https://github.com/capistrano/bundler
#   https://github.com/capistrano/rails
#   https://github.com/capistrano/passenger
#
# require "capistrano/rvm"
# require "capistrano/rbenv"
# require "capistrano/chruby"
# require "capistrano/bundler"
# require "capistrano/rails/assets"
# require "capistrano/rails/migrations"
# require "capistrano/passenger"

# Load custom tasks from `lib/capistrano/tasks` if you have any defined
Dir.glob("lib/capistrano/tasks/*.rake").each { |r| import r }

```

#### config/deploy.rb
``` ruby
# config valid for current version and patch releases of Capistrano
lock "~> 3.16.0"

set :application, "favimo"
set :repo_url, "git@github.com:hasyrails/favimo.git"
set :deploy_to, '/var/www/rails'

# Default branch is :master
# ask :branch, `git rev-parse --abbrev-ref HEAD`.chomp

# Default deploy_to directory is /var/www/my_app_name
# set :deploy_to, "/var/www/my_app_name"

# Default value for :format is :airbrussh.
# set :format, :airbrussh

# You can configure the Airbrussh format using :format_options.
# These are the defaults.
# set :format_options, command_output: true, log_file: "log/capistrano.log", color: :auto, truncate: :auto

# Default value for :pty is false
# set :pty, true

# Default value for :linked_files is []
# append :linked_files, "config/database.yml"

# Default value for linked_dirs is []
# append :linked_dirs, "log", "tmp/pids", "tmp/cache", "tmp/sockets", "public/system"

# Default value for default_env is {}
# set :default_env, { path: "/opt/ruby/bin:$PATH" }

# Default value for local_user is ENV['USER']
# set :local_user, -> { `git config user.name`.chomp }

# Default value for keep_releases is 5
# set :keep_releases, 5

# Uncomment the following to require manually verifying the host key before first deploy.
# set :ssh_options, verify_host_key: :secure

namespace :deploy do
  desc "Make sure local git is in sync with remote."

  task :confirm do
    on roles(:app) do
      puts "This stage is '#{fetch(:stage)}'. Deploying branch is '#{fetch(:branch)}'."
      puts 'Are you sure? [y/n]'
      ask :answer, 'n'
      if fetch(:answer) != 'y'
        puts 'deploy stopped'
        exit
      end
    end
  end

  desc 'Initial Deploy'
  task :initial do
    on roles(:app) do
      invoke 'deploy'
    end
  end
  
  before :starting, :confirm
end
```

#### config/deploy/production.rb
``` ruby
# server-based syntax
# ======================
# Defines a single server with a list of roles and multiple properties.
# You can define all roles on a single server, or split them:

# server "example.com", user: "deploy", roles: %w{app db web}, my_property: :my_value
# server "example.com", user: "deploy", roles: %w{app web}, other_property: :other_value
# server "db.example.com", user: "deploy", roles: %w{db}

server "18.180.42.246", user: "hasyrails", roles: %w{app db web}
set :repo_url, "https://github.com/hasyrails/favimo.git"
set :application, "favimo"
set :ssh_options, {
  keys: %w(~/.ssh/favimo_rsa_hasyrails),
  forward_agent: true,
  auth_methods: %w(publickey)
}
set :use_sudo, true


# role-based syntax
# ==================

# Defines a role with one or multiple servers. The primary server in each
# group is considered to be the first unless any hosts have the primary
# property set. Specify the username and a domain or IP for the server.
# Don't use `:all`, it's a meta role.

# role :app, %w{deploy@example.com}, my_property: :my_value
# role :web, %w{user1@primary.com user2@additional.com}, other_property: :other_value
# role :db,  %w{deploy@example.com}



# Configuration
# =============
# You can set any configuration variable like in config/deploy.rb
# These variables are then only loaded and set in this stage.
# For available Capistrano configuration variables see the documentation page.
# http://capistranorb.com/documentation/getting-started/configuration/
# Feel free to add new variables to customise your setup.



# Custom SSH Options
# ==================
# You may pass any option but keep in mind that net/ssh understands a
# limited set of options, consult the Net::SSH documentation.
# http://net-ssh.github.io/net-ssh/classes/Net/SSH.html#method-c-start
#
# Global options
# --------------
#  set :ssh_options, {
#    keys: %w(/home/user_name/.ssh/id_rsa),
#    forward_agent: false,
#    auth_methods: %w(password)
#  }
#
# The server-based syntax can be used to override options:
# ------------------------------------
# server "example.com",
#   user: "user_name",
#   roles: %w{web app},
#   ssh_options: {
#     user: "user_name", # overrides user setting above
#     keys: %w(/home/user_name/.ssh/id_rsa),
#     forward_agent: false,
#     auth_methods: %w(publickey password)
#     # password: "please use keys"
#   }

```

**Comment by hasyrails** [comment]
### エラー対処方針
[Error: Permission denied (publickey) - GitHub Docs](https://docs.github.com/ja/github/authenticating-to-github/error-permission-denied-publickey)

**Comment by hasyrails** [comment]
### [Check that you are connecting to the correct server](https://docs.github.com/ja/github/authenticating-to-github/error-permission-denied-publickey#check-that-you-are-connecting-to-the-correct-server)
```
[hasyrails@ip-xx-x-x-xxx ~]$ ssh -vT git@github.com

OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017
debug1: Reading configuration data /home/hasyrails/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 58: Applying options for *
debug1: Connecting to github.com [52.192.72.89] port 22.
debug1: Connection established.
debug1: identity file /home/hasyrails/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/hasyrails/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.4
debug1: Remote protocol version 2.0, remote software version babeld-517b8896
debug1: no match: babeld-517b8896
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: kex: curve25519-sha256 need=64 dh_need=64
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
debug1: Host 'github.com' is known and matches the RSA host key.
debug1: Found key in /home/hasyrails/.ssh/known_hosts:1
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /home/hasyrails/.ssh/id_rsa
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/hasyrails/.ssh/id_dsa
debug1: Trying private key: /home/hasyrails/.ssh/id_ecdsa
debug1: Trying private key: /home/hasyrails/.ssh/id_ed25519
debug1: No more authentication methods to try.
Permission denied (publickey).
```

**Comment by hasyrails** [comment]
### **ローカルで**鍵設定する
下記参考を**ローカルで**設定したら解決した
[Gitでssh/cloneした時にPermission denied (publickey). - メンチカツには醤油でしょ!!](https://ryoichi0102.hatenablog.com/entry/2017/02/03/232920)
