### ISSUE TITLE
deploy06 / Capistranoによるassets precompileができない

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#282]
### Capistranoエラーログ 
```
00:54 deploy:assets:precompile
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 yarn install v1.22.5
      01 warning package-lock.json found. Your project contains lock files generated by tools other…
      01 [1/4] Resolving packages...
      01 [2/4] Fetching packages...
      01 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
      01 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding …
      01 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
      01 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding…
      01 [3/4] Linking dependencies...
      01 warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0…
      01 warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "web…
      01 [4/4] Building fresh packages...


make: *** [Release/obj.target/binding/src/binding.o] エラー 1
make: ディレクトリ `/var/www/favimo/shared/node_modules/node-sass/build' から出ます
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/favimo/shared/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 4.14.231-173.360.amzn2.x86_64
gyp ERR! command "/home/hasyrails/.nvm/versions/node/v16.0.0/bin/node" "/var/www/favimo/shared/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/favimo/shared/node_modules/node-sass
gyp ERR! node -v v16.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1


** DEPLOY FAILED
** Refer to log/capistrano.log for details. Here are the last 20 lines:


                                                               ^~~~~~~

/home/hasyrails/.node-gyp/16.0.0/include/node/v8-internal.h:452:63: 備考: suggested alternative: ‘herror’

             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);

                                                               ^~~~~~~

                                                               herror

make: *** [Release/obj.target/binding/src/binding.o] エラー 1

make: ディレクトリ `/var/www/favimo/shared/node_modules/node-sass/build' から出ます

gyp ERR! build error 

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit (/var/www/favimo/shared/node_modules/node-gyp/lib/build.js:262:23)

gyp ERR! stack     at ChildProcess.emit (node:events:365:28)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)

gyp ERR! System Linux 4.14.231-173.360.amzn2.x86_64

gyp ERR! command "/home/hasyrails/.nvm/versions/node/v16.0.0/bin/node" "/var/www/favimo/shared/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="

gyp ERR! cwd /var/www/favimo/shared/node_modules/node-sass

gyp ERR! node -v v16.0.0

gyp ERR! node-gyp -v v3.8.0

gyp ERR! not ok 

Build failed with error code: 1

 DEBUG [ef77a1f4] 	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### EC2インスタンスの環境
```
[EC2インスタンスサーバー環境]$ node -v
v16.0.0
```

```
[ローカル環境] $ node -v
v12.18.1

```

**Comment by hasyrails** [comment]
### 行ったこと
#### ①rebuildコマンド
 - EC2インスタンスサーバー
 - ローカル
のどちらも下記コマンドを実行
```
 npm rebuild node-sass
```
[Nodeのバージョンを上げたらnode-sassがエラーを吐いたのでコードリーディングしてみた | DevelopersIO](https://dev.classmethod.jp/articles/node-sass-could-not-find-a-binding/)

#### node.jsのバージョンを下げる
```
[hasyrails@ip-10-0-1-117 ~]$ nvm ls-remote
‥
       v14.15.0   (LTS: Fermium)
       v14.15.1   (LTS: Fermium)
       v14.15.2   (LTS: Fermium)
       v14.15.3   (LTS: Fermium)
       v14.15.4   (LTS: Fermium)
       v14.15.5   (LTS: Fermium)
       v14.16.0   (LTS: Fermium)
       v14.16.1   (Latest LTS: Fermium)
‥
->      v16.0.0

```
