### ISSUE TITLE
deploy_07 / capistrano assets:precompileでエラー

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#291]
```
01:28 deploy:assets:precompile
      01 $HOME/.rbenv/bin/rbenv exec bundle exec rake assets:precompile
      01 yarn install v1.22.5
      01 warning package-lock.json found. Your project contains lock files generated by tools other…
      01 [1/4] Resolving packages...
      01 [2/4] Fetching packages...
      01 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
      01 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding …
      01 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
      01 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding…
      01 [3/4] Linking dependencies...
      01 warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0…
      01 warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "web…
      01 [4/4] Building fresh packages...
      01 Done in 28.00s.
      01 yarn install v1.22.5
      01 warning package-lock.json found. Your project contains lock files generated by tools other…
      01 [1/4] Resolving packages...
      01 [2/4] Fetching packages...
      01 info fsevents@2.3.2: The platform "linux" is incompatible with this module.
      01 info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding …
      01 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
      01 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding…
      01 [3/4] Linking dependencies...
      01 warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0…
      01 warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "web…
      01 [4/4] Building fresh packages...
      01 Done in 4.81s.
      01 rake aborted!
      01 LoadError: cannot load such file -- sassc
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in …
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/autoload/sassc…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/bootsnap-1.7.3/lib/bootsnap/load_path_cache/…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in …
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/sassc_processo…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/sassc_processo…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/sassc_processo…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/sassc_processo…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/cached_environ…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:41:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/utils.rb:167:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:42:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/cached_environ…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:32:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/bundle.rb:31:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/processor_util…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:182:…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:59:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:337:…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/loader.rb:43:i…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/cached_environ…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:81:in …
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/base.rb:88:in …
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/sprockets-4.0.2/lib/sprockets/manifest.rb:12…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 /var/www/favimo/shared/bundle/ruby/2.6.0/gems/concurrent-ruby-1.1.8/lib/concurrent-ruby/co…
      01 Tasks: TOP => assets:precompile
      01 (See full trace by running task with --trace)
#<Thread:0x00007fb88bba9320@/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:10 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	13: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
	12: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `run'
	11: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:31:in `instance_exec'
	10: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-rails-1.6.1/lib/capistrano/tasks/assets.rake:67:in `block (4 levels) in <top (required)>'
	 9: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:92:in `within'
	 8: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-rails-1.6.1/lib/capistrano/tasks/assets.rake:68:in `block (5 levels) in <top (required)>'
	 7: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:100:in `with'
	 6: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/capistrano-rails-1.6.1/lib/capistrano/tasks/assets.rake:69:in `block (6 levels) in <top (required)>'
	 5: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:80:in `execute'
	 4: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `create_command_and_execute'
	 3: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `tap'
	 2: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/abstract.rb:148:in `block in create_command_and_execute'
	 1: from /Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/backends/netssh.rb:170:in `execute_command'
/Users/shota/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/sshkit-1.21.2/lib/sshkit/command.rb:97:in `exit_status=': rake exit status: 1 (SSHKit::Command::Failed)
rake stdout: yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 28.00s.
yarn install v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
Done in 4.81s.
rake stderr: warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning " > webpack-dev-server@3.11.2" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "webpack-dev-server > webpack-dev-middleware@3.7.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
rake aborted!
LoadError: cannot load such file -- sassc
```

**Comment by hasyrails** [comment]
### ```LoadError: cannot load such file -- sassc```と書いてあるため
 - sassに関連するファイルを探した
 - Gemfileを見てみた

``` ruby
# Use SCSS for stylesheets
# gem 'sass-rails', '>= 6' # コメントアウトされている！

```
→ コメントアウトを外したら無事デプロイ完了！
