### ISSUE TITLE
deploy_07 / 本番環境で画像登録しようとするとWe're sorry, but something went wrong.

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#294]
### 現状
プロフィール画面で画像変更をしようと画像登録・保存の
リクエストを送ると
We're sorry, but something went wrong.

### エラーログ 
```
[2021-05-03T10:42:18.878721 #23644]  INFO -- : [45b9795c-565d-4077-a975-d4bc231966c2] Completed 500 Internal Server Error in 178ms (ActiveRecord: 23.9ms | Allocations: 15568)
F, [2021-05-03T10:42:18.879397 #23644] FATAL -- : [45b9795c-565d-4077-a975-d4bc231966c2]   
[45b9795c-565d-4077-a975-d4bc231966c2] Excon::Error::Forbidden (Expected(200) <=> Actual(403 Forbidden)
excon.error.response
  :body          => "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>70T7S5VG0AJKS8V7</RequestId><HostId>70kZQ/VtT+NJvDnEf3WzSyCWC0LwRb3N8XGPVg16cp6VpYzKSdv5/YGmomQIytDd1/zve9Ll+Hg=</HostId></Error>"
  :cookies       => [
  ]
  :headers       => {
    "Connection"       => "close"
    "Content-Type"     => "application/xml"
    "Date"             => "Mon, 03 May 2021 10:42:18 GMT"
    "Server"           => "AmazonS3"
    "x-amz-id-2"       => "70kZQ/VtT+NJvDnEf3WzSyCWC0LwRb3N8XGPVg16cp6VpYzKSdv5/YGmomQIytDd1/zve9Ll+Hg="
    "x-amz-request-id" => "70T7S5VG0AJKS8V7"
  }
  :host          => "favimo-bucket.s3.ap-northeast-1.amazonaws.com"
  :local_address => "10.0.1.237"
  :local_port    => 41670
  :path          => "/uploads/tmp/1620038538-655011910121108-0002-3245/neco.jpeg"
  :port          => 443
  :reason_phrase => "Forbidden"
  :remote_ip     => "52.219.136.143"
  :status        => 403
  :status_line   => "HTTP/1.1 403 Forbidden\r\n"
):
[45b9795c-565d-4077-a975-d4bc231966c2]   
[45b9795c-565d-4077-a975-d4bc231966c2] app/models/user.rb:35:in `update_without_current_password'
[45b9795c-565d-4077-a975-d4bc231966c2] app/controllers/registrations_controller.rb:8:in `update_resource'
E, [2021-05-03T10:42:18.987193 #23644] ERROR -- : WebSocket error occurred: Broken pipe
I, [2021-05-03T10:42:18.987563 #23644]  INFO -- : Finished "/cable/" [WebSocket] for 111.239.252.114 at 2021-05-03 10:42:18 +0000
E, [2021-05-03T10:42:18.988250 #23644] ERROR -- : There was an exception - Gem::LoadError(Error loading the 'redis' Action Cable pubsub adapter. Missing a gem it depends on? redis is not part of the bundle. Add it to your Gemfile.)
E, [2021-05-03T10:42:18.988304 #23644] ERROR -- : /home/hasyrails/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/bundler-2.2.16/lib/bundler/rubygems_integration.rb:334:in `block (2 levels) in replace_gem'
‥
```

**Comment by hasyrails** [comment]
### 解消
IAMユーザーのポリシーを
カスタムポリシー → AmazonS3FullAccess へ変更
