### ISSUE TITLE
Rails + js / gonで設定したパラメータがスワイプアクションで渡っていない

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#64]
### gem gon
Gemfile
``` ruby
gem 'gon'
```

### ```VideosController.rb```
``` ruby
  def index
    if params[:keyword].present?
      @youtube_videos = find_videos(params[:keyword])
      gon.youtube_videos = @youtube_videos
      gon.title = 'ダミータイトル' 
    else
      @youtube_videos = find_videos('')
      gon.youtube_videos = @youtube_videos
      gon.title = 'ダミータイトル'
    end
  end
```

### ```video_swipe.js```
``` js
$.ajax({
        url: "videos",
        type: "POST",
        datatype: "json",
        data: {
          user_id: user_id,
          reaction: reaction,
          title: gon.title
        }
      })
```

**Comment by hasyrails** [comment]
### 動画スワイプ時のターミナルログ
```gon.title```がスワイプ時に現れない

```
Started POST "/youtube/videos" for ::1 at 2021-01-24 09:33:07 +0900
Processing by Youtube::VideosController#create as */*
  Parameters: {"user_id"=>"", "reaction"=>"like"}
  User Load (1.6ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/youtube/videos_controller.rb:7:in `create'
   (0.2ms)  BEGIN
  ↳ app/controllers/youtube/videos_controller.rb:6:in `create'
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/youtube/videos_controller.rb:6:in `create'
  YoutubeVideo Create (2.2ms)  INSERT INTO "youtube_videos" ("status", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["status", 0], ["user_id", 2], ["created_at", "2021-01-24 00:33:07.697023"], ["updated_at", "2021-01-24 00:33:07.697023"]]
  ↳ app/controllers/youtube/videos_controller.rb:6:in `create'
   (1.1ms)  COMMIT
  ↳ app/controllers/youtube/videos_controller.rb:6:in `create'
No template found for Youtube::VideosController#create, rendering head :no_content
Completed 204 No Content in 45ms (ActiveRecord: 5.3ms | Allocations: 16093)
```

**Comment by hasyrails** [comment]
### gon自体が機能していない
トップページで基本的なウィンドウアラートを発生させるコードとしたが
アラート発火せず

**Comment by hasyrails** [comment]
### 方針変更
gem gon を使用しないことへ変更
