### ISSUE TITLE
Rails / 動画レコードのLike/DisLikeが更新されない

### ISSUE THREAD

**Issue by hasyrails** [hasyrails/favimo#85]
```
Started POST "/youtube/myvideos/favorites.json" for ::1 at 2021-02-09 07:22:11 +0900
Processing by Youtube::Myvideos::FavoritesController#create as JSON
  Parameters: {"youtube_video_id"=>"29", "favorite"=>"like"}
  User Load (1.8ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/youtube/myvideos/favorites_controller.rb:5:in `create'
   (1.3ms)  BEGIN
  ↳ app/controllers/youtube/myvideos/favorites_controller.rb:3:in `create'
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/youtube/myvideos/favorites_controller.rb:3:in `create'
  YoutubeVideo Load (1.0ms)  SELECT "youtube_videos".* FROM "youtube_videos" WHERE "youtube_videos"."id" = $1 LIMIT $2  [["id", 29], ["LIMIT", 1]]
  ↳ app/controllers/youtube/myvideos/favorites_controller.rb:3:in `create'
  Favorite Create (1.3ms)  INSERT INTO "favorites" ("user_id", "youtube_video_id", "status", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["user_id", 2], ["youtube_video_id", 29], ["status", 0], ["created_at", "2021-02-08 22:22:11.605845"], ["updated_at", "2021-02-08 22:22:11.605845"]]
  ↳ app/controllers/youtube/myvideos/favorites_controller.rb:3:in `create'
   (1.9ms)  COMMIT
  ↳ app/controllers/youtube/myvideos/favorites_controller.rb:3:in `create'
No template found for Youtube::Myvideos::FavoritesController#create, rendering head :no_content
Completed 204 No Content in 25ms (ActiveRecord: 7.6ms | Allocations: 6093)
```

**Comment by hasyrails** [comment]
よく見たら反映されてた
